### ISSUE TITLE
Missing parameter in AttributeDefinition

### ISSUE THREAD

**Issue by michael-82** [medizininformatik-initiative/feasibility-backend#342]
Change the parameters to the way they are mentioned in the swagger documentation, since this was consented on.

```yaml
        referencedCriteriaSet:
          type: string
          example: "http://fdpg.mii.cds/CriteriaSet/Diagnose/icd-10-gm"
        referencedValueSet:
          type: string
          example: "http://hl7.org/fhir/sid/icd-o-3"
```
