### ISSUE TITLE
Change management endpoint configuration

### ISSUE THREAD

**Issue by michael-82** [medizininformatik-initiative/feasibility-backend#462]
The following settings are deprecated

```yaml
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
```
and should be replaced by default access "none" and health "unrestricted"

See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#controlling-access-to-actuator-endpoints
